function [fitresult, gof] = fitCpvsPseudospin(gamma,Cp,varargin)
%CREATEFIT(GAMMA,CP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : gamma
%      Y Output: Cp
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Oct-2018 09:47:23

%% Added optional argument on 2018-10-07
% See https://blogs.mathworks.com/loren/2009/05/05/nice-way-to-set-function-defaults/
% And https://www.mathworks.com/matlabcentral/answers/217363-how-to-support-default-parameter-in-matlab-function
nvarargs = length(varargin);
optargs = {'C_p (J\cdotmol^{-1}\cdotK^{-1})'};
optargs(1:nvarargs) = varargin;
[ylbl] = optargs{:};% The optional argument defines the label of the y axis of the plot


%% Fit: 'Cp vs total pseudospin'.
[xData, yData] = prepareCurveData( gamma, Cp );

% Set up fittype and options.
ft = fittype( 'A*(atanh(2*x))^2*(1-4*x^2)/(1-(1-4*x^2)*atanh(2*x)/(2*x))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = 0.868155684306992;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'MF fit' );
h = plot( fitresult, xData, yData );
legend( h, 'Cp vs. gamma', 'MF fit', 'Location', 'NorthEast' );
% Label axes
xlabel 'Total pseudospin'
ylabel(ylbl)
title 'Mean-field fit of heat capacity vs total pseudospin'
grid on

