function [fitresult, gof] = fitCpTFIM(T,Cp,wghts,Tc0,h)
%CREATEFIT(T1,CP1,WGHTS1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : T1
%      Y Output: Cp1
%      Weights : wghts1
%      Tc0     : value of transition temperature under zero magnetic field
%      hc      : reduced magnetic field H/Hc
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Mar-2019 15:27:36

if h==0; tc = 1;
elseif abs(h)<1; tc = h/atanh(h);
else; tc = 0;
end
tc = tc * Tc0;% tc is the transition temperature of the data to be fitted,
% calculated as a function of the transition temperature under zero
% magnetic field

%% Fit: 'untitled fit 1'.
[xData, yData, weights] = prepareCurveData( T, Cp, wghts );

% Set up fittype and options.
ft = fittype( sprintf('a*Cp_TFIM(t/%d,%d)',Tc0,h), 'independent', 't', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'Domain', [0 0.87*tc] );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = 0;
opts.StartPoint = 1;
opts.Weights = weights;
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
Xfit = linspace(0,max(T),1000);
Yfit = fitresult(Xfit);% compute fit over a controlled number of points
figure;
hold on
pfit = plot(Xfit,Yfit,'r-');
pdat = errorbar(xData,yData,1./wghts,'xb','MarkerSize',12,'LineWidth',2);
pexcl = plot(xData(excludedPoints),yData(excludedPoints),'xg',...
    'MarkerSize',12);
legend([pdat,pexcl,pfit],'Cp vs T','Excluded','MF fit');
% Label axes
xlabel T(K); ylabel Cp(uJ/K); grid on



