function ImportMCEinDR = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   MCETMVO4LS5228DRHC180731 = IMPORTFILE(FILENAME) Reads data from text
%   file FILENAME for the default selection.
%
%   MCETMVO4LS5228DRHC180731 = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads
%   data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   MCETmVO4LS5228DRHC180731 = importfile('2018-08-01_MCE_TmVO4-LS5228-DR-HC180731.dat', 1, 23644);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/08/06 12:19:46

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Split data into numeric and string columns.
rawNumericColumns = raw(:, [2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42]);
rawStringColumns = string(raw(:, [1,3]));


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Make sure any text containing <undefined> is properly converted to an <undefined> categorical
idx = (rawStringColumns(:, 1) == "<undefined>");
rawStringColumns(idx, 1) = "";

%% Create output variable
ImportMCEinDR = table;
% ImportMCEinDR.Comment = categorical(rawStringColumns(:, 1));
ImportMCEinDR.TimeStampsec = cell2mat(rawNumericColumns(:, 1));
% ImportMCEinDR.Statuscode = cellstr(rawStringColumns(:, 2));
ImportMCEinDR.TemperatureK = cell2mat(rawNumericColumns(:, 2));
ImportMCEinDR.MagneticFieldOe = cell2mat(rawNumericColumns(:, 3));
% ImportMCEinDR.Bridge1ResistivityOhmm = cell2mat(rawNumericColumns(:, 5));
% ImportMCEinDR.Bridge1ExcitationuA = cell2mat(rawNumericColumns(:, 6));
ImportMCEinDR.Bridge2ResistivityOhmm = cell2mat(rawNumericColumns(:, 7));
ImportMCEinDR.Bridge2ExcitationuA = cell2mat(rawNumericColumns(:, 8));
% ImportMCEinDR.Bridge1StdDevOhmm = cell2mat(rawNumericColumns(:, 13));
ImportMCEinDR.Bridge2StdDevOhmm = cell2mat(rawNumericColumns(:, 14));
% ImportMCEinDR.NumberofReadings = cell2mat(rawNumericColumns(:, 17));
% ImportMCEinDR.Bridge1ResistanceOhms = cell2mat(rawNumericColumns(:, 18));
ImportMCEinDR.Bridge2ResistanceOhms = cell2mat(rawNumericColumns(:, 19));
