function S = importCpDR(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   DRHC10YTMVO4LS5251DRHC180511 = IMPORTFILE(FILENAME) Reads data from
%   text file FILENAME for the default selection.
%
%   DRHC10YTMVO4LS5251DRHC180511 = IMPORTFILE(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   DRHC10YTmVO4LS5251DRHC180511 = importfile('DRHC_10YTmVO4-LS5251-DR-HC180511.dat', 1, 203);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/05/25 11:20:39

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,22,26,27,28,29,30]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Split data into numeric and string columns.
rawNumericColumns = raw(:, [1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,22,26,27,28,29,30]);
rawStringColumns = string(raw(:, [2,20,21,23,24,25]));


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
S = table;
S.TimeStampSeconds = cell2mat(rawNumericColumns(:, 1));
S.Comment = cellstr(rawStringColumns(:, 1));
S.SystemStatusCode = cell2mat(rawNumericColumns(:, 2));
S.PuckTempKelvin = cell2mat(rawNumericColumns(:, 3));
S.SystemTempKelvin = cell2mat(rawNumericColumns(:, 4));
S.FieldOersted = cell2mat(rawNumericColumns(:, 5));
S.PressureTorr = cell2mat(rawNumericColumns(:, 6));
S.SampleTempKelvin = cell2mat(rawNumericColumns(:, 7));
S.TempRiseKelvin = cell2mat(rawNumericColumns(:, 8));
S.SampHCJK = cell2mat(rawNumericColumns(:, 9));
S.SampHCErrJK = cell2mat(rawNumericColumns(:, 10));
S.AddendaHCJK = cell2mat(rawNumericColumns(:, 11));
S.AddendaHCErrJK = cell2mat(rawNumericColumns(:, 12));
S.TotalHCJK = cell2mat(rawNumericColumns(:, 13));
S.TotalHCErrJK = cell2mat(rawNumericColumns(:, 14));
S.FitDeviationChiSquare = cell2mat(rawNumericColumns(:, 15));
S.TimeConsttau1seconds = cell2mat(rawNumericColumns(:, 16));
S.TimeConsttau2seconds = cell2mat(rawNumericColumns(:, 17));
S.SampleCouplingPercent = cell2mat(rawNumericColumns(:, 18));
S.DebyeTempKelvin = cellstr(rawStringColumns(:, 2));
S.DebyeTempErrKelvin = cellstr(rawStringColumns(:, 3));
S.CalCorrectionFactor = cell2mat(rawNumericColumns(:, 19));
S.ThermResistOhms = cellstr(rawStringColumns(:, 4));
S.HtrResistOhms = cellstr(rawStringColumns(:, 5));
S.PuckResistOhms = cellstr(rawStringColumns(:, 6));
S.WireCondWK = cell2mat(rawNumericColumns(:, 20));
S.MeasTimeseconds = cell2mat(rawNumericColumns(:, 21));
S.TempSquaredK2 = cell2mat(rawNumericColumns(:, 22));
S.SampHCTempJKK = cell2mat(rawNumericColumns(:, 23));
S.AddendaOffsetHCJK = cell2mat(rawNumericColumns(:, 24));

