function [fitresult, gof] = ENS_peak_fit_ICpV_function_3params(hh0, I, hCenter)
%CREATEFIT(HH067,I67)
%  Create a fit.
%
%  Data for 'ICpV' (Ikeda-Carpenter-pseudo-Voigt) fit:
%      X Input (numeric array): hh0, cut of data along hh0 direction
%      Y Input (numeric array): I, neutrons intensity received by detector, in arb. units
%      hCenter (integer): center of peak, in reciprocal space units 
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Feb-2019 19:01:29


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData(hh0,I);
dataExcl = hh0<hCenter-.15 | hh0>hCenter+0.2;
peak1InitCenter = hCenter*1.0025;
peak2InitCenter = hCenter*0.9975;

% Set up fittype and options.
ft = fittype( 'I*voigtIkedaCarpenter(x,[gamma,0.0066,1.38e+02,1,0,0.05,x0])', 'independent', 'x', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'Indices', dataExcl );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 -Inf];
opts.StartPoint = [200000 0.01 -8];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData, excludedPoints );
% legend( h, 'I vs. hh0', 'Excluded I vs. hh0', 'fit ICpV', 'Location', 'NorthEast' );
% % Label axes
% xlabel("hh0")
% ylabel("I (a.u.)")
% grid on


