function Cp_TFIM_HT_MEC(T,B,aa,bb,ee)
Cp2 = (-1/4).*B.*k.^(-1).*p.^(-2).*(aa+(-1).*T).^(-4).*T.^(-2).*((-4).* ...
  k.*p.*(aa+(-1).*T).^2.*T.*tanh((1/2).*B.*k.^(-1).*p.^(-1).*T.^(-1) ...
  .*((-1).*aa+T).^(-1).*(ee.*p.*((-1).*aa+T)+B.*((-1).*bb+T).*S(T))) ...
  .*(B.*(aa.*bb+T.*((-2).*bb+T)).*S(T)+(aa+(-1).*T).*(ee.*p.*(aa+( ...
  -1).*T)+B.*T.*((-1).*bb+T).*Derivative(1)(S)(T)))+B.*sech((1/2).* ...
  B.*k.^(-1).*p.^(-1).*T.^(-1).*((-1).*aa+T).^(-1).*(ee.*p.*((-1).* ...
  aa+T)+B.*((-1).*bb+T).*S(T))).^2.*(B.*(aa.*bb+T.*((-2).*bb+T)).*S( ...
  T)+(aa+(-1).*T).*(ee.*p.*(aa+(-1).*T)+B.*T.*((-1).*bb+T).* ...
  Derivative(1)(S)(T))).^2+2.*k.*p.*(aa+(-1).*T).*T.*tanh((1/2).*B.* ...
  k.^(-1).*p.^(-1).*T.^(-1).*((-1).*aa+T).^(-1).*(ee.*p.*((-1).*aa+ ...
  T)+B.*((-1).*bb+T).*S(T))).*(2.*B.*(aa.^2.*bb+(-3).*aa.*bb.*T+(3.* ...
  bb+(-1).*T).*T.^2).*S(T)+(aa+(-1).*T).*((-2).*B.*T.*(aa.*bb+T.*(( ...
  -2).*bb+T)).*Derivative(1)(S)(T)+(aa+(-1).*T).*(2.*ee.*p.*(aa+(-1) ...
  .*T)+B.*(bb+(-1).*T).*T.^2.*Derivative(2)(S)(T)))));
% Heat capacity derived from magneto-elastic coupling including external
% constant longitudinal strain ee in TFIM