%% Analysis of capacitance data generated by the capacitance bridge on the ICE Oxford cryostat
cd 'C:\Users\Pierre\Desktop\Postdoc\TmAsO4\TmAsO4_capacitance\TmAsO4-LS342-C1909';
% FullData=ImportMCEinDRmatrix('2018-08-01_MCE_TmVO4-LS5228-DR-HC180731.dat');%
Data = ImportCapICEHe4('2019-09-16_TmAsO4-LS342-Cab1909_02.txt');

%% Capacitance vs time
figure
plot(Data.time_s,Data.C_pF)
xlabel('time (s)'); ylabel('$C$ (pF)');

%% Capacitance vs Temperature
figure
plot(Data.T_K,Data.C_pF)
xlabel('$T$ (K)'); ylabel('$C$ (pF)');

%% Compute temperature derivative of capacitance
% Create table column containing differences of temperature column
diffT = diff(Data.T_K);
Data.diffT = zeros(size(Data.T_K));
Data.diffT(2:end-1) = (diffT(2:end)+diffT(1:end-1))/2;
Data.diffT(1) = diffT(1)/2; Data.diffT(end) = diffT(end)/2;

% Create table column containing differences of capacitance column
diffC = diff(Data.C_pF);
Data.diffC = zeros(size(Data.C_pF));
Data.diffC(2:end-1) = (diffC(2:end)+diffC(1:end-1))/2;
Data.diffC(1) = diffC(1)/2; Data.diffC(end) = diffC(end)/2;

% Compute dC/dT
Data.dCdT = Data.diffC./Data.diffT;

%% Separate temperature up- and downsweeps
% Using boolean filter
FilterTup = Data.dT > 1e-3;% logical array, the elements of which equal 1 when temperature is swept up
FilterTdown = Data.dT < -1e-3;% same when temperature is swept down

%% Plot capacitance data for temperature upsweeps
figure
plot(Data.T_K(FilterTup),Data.C_pF(FilterTup),'.','MarkerSize',12)
xlabel('$T$ (K)'); ylabel('$C$ (pF)');

%% Split up- and downsweeps into individual arrays
dFup = diff(FilterTup);% Array where elements are non-zero only when a new upsweep starts or ends
dFdown = diff(FilterTdown);% Same for downsweep
upStart = find(dFup>0);% dFup=1 when an upsweep starts
upEnd = find(dFup<0);% dFup=-1 when an upsweep ends
downStart = find(dFdown>0); downEnd = find(dFdown<0);% Same for downsweeps
sgm = 1;
for i=1:length(upStart)
    up(i).T = Data.T_K(upStart(i):upEnd(i));
    up(i).diffT = Data.diffT(upStart(i):upEnd(i));
    up(i).C = Data.C_pF(upStart(i):upEnd(i));
    up(i).dCdT = Data.dCdT(upStart(i):upEnd(i));
    [up(i).gC,up(i).gdC,~] = gConvolve(Data.C_pF(upStart(i):upEnd(i)),sgm);
    [up(i).gT,up(i).gdT,~] = gConvolve(Data.T_K(upStart(i):upEnd(i)),sgm);
end

for i=1:length(downStart)
    down(i).T = Data.T_K(downStart(i):downEnd(i));
    down(i).C = Data.C_pF(downStart(i):downEnd(i));
    down(i).dCdT = Data.dCdT(downStart(i):downEnd(i));
    [down(i).gC,down(i).gdC,~] = gConvolve(Data.C_pF(downStart(i):downEnd(i)),sgm);
    [down(i).gT,down(i).gdT,~] = gConvolve(Data.T_K(downStart(i):downEnd(i)),sgm);
end

%% Plot capacitance data for separate temperature upsweeps
figure; hold on
for i=1:length(up)
plot(up(i).T,up(i).C,'.','MarkerSize',12,'DisplayName',sprintf('%i',i))
end
xlabel('$T$ (K)'); ylabel('$C$ (pF)');
title('Capacitance vs Temperature swept up');
lgd = legend('show'); lgd.Title.String = 'Run \#';

%% Plot capacitance data for separate temperature downsweeps
figure; hold on
for i=1:length(down)
plot(down(i).T,down(i).C,'.','MarkerSize',12,'DisplayName',sprintf('%i',i))
end
xlabel('$T$ (K)'); ylabel('$C$ (pF)');
title('Capacitance vs Temperature swept down');
lgd = legend('show'); lgd.Title.String = 'Run \#';

%% Compare raw and smoothed data
i=1;
Cbounds = [.452 .458];
figure; hold on
plot(up(i).T,up(i).C,'-','MarkerSize',12,'DisplayName','Raw')
plot(up(i).T,up(i).gC,'-','MarkerSize',12,'DisplayName',['Smoothed $\sigma=$' sprintf('%g',sgm)])
xlabel('$T$ (K)'); ylabel('$C$ (pF)');
title('Effect of smoothing');
lgd = legend('show');
ylim(Cbounds);

%% Compare raw and smoothed derivative
i=1;
figure; hold on
plot(up(i).T,up(i).dCdT,'-','MarkerSize',12,'DisplayName','Raw')
plot(up(i).T,up(i).gdC./up(i).diffT,'-','MarkerSize',12,'DisplayName',['Smoothed $\sigma=$' sprintf('%g',sgm)])
plot(up(i).T,up(i).gdC./up(i).gdT,'-','MarkerSize',12,'DisplayName',['Smoothed $\sigma=$' sprintf('%g',sgm)])
xlabel('$T$ (K)'); ylabel('$dC/dT$ (pF/K)');
title('Effect of smoothing on temperature derivative');
lgd = legend('show');
ylim(Cbounds);

%% Plot smoothed capacitance vs temperature
figure; hold on
for i=1:length(up)
plot(up(i).T,up(i).gC,'.','MarkerSize',12,'DisplayName',sprintf('%i',i))
end
xlabel('$T$ (K)'); ylabel('$C$ (pF)');
title('Capacitance vs Temperature swept up');
lgd = legend('show'); lgd.Title.String = 'Run \#';
ylim(Cbounds);

%% Plot smoothed capacitance vs temperature
figure; hold on
for i=1:length(down)
plot(down(i).T,down(i).gC,'.','MarkerSize',12,'DisplayName',sprintf('%i',i))
end
xlabel('$T$ (K)'); ylabel('$C$ (pF)');
title('Capacitance vs Temperature swept down');
lgd = legend('show'); lgd.Title.String = 'Run \#';
ylim(Cbounds);

%% Plot smoothed dC/dT vs temperature
d1Cbounds = [-.02 .02];
figure; hold on
for i=1:length(up)
plot(up(i).T,up(i).gdC./up(i).gdT,'.-','MarkerSize',12,'DisplayName',sprintf('%i',i))
end
xlabel('$T$ (K)'); ylabel('$C$ (pF)');
title('$dC/dT$ vs Temperature swept up');
lgd = legend('show'); lgd.Title.String = 'Run \#';
ylim(d1Cbounds);

%% Plot smoothed dC/dT vs temperature
figure; hold on
for i=1:length(down)
plot(down(i).T,down(i).gdC./down(i).gdT,'.-','MarkerSize',12,'DisplayName',sprintf('%i',i))
end
xlabel('$T$ (K)'); ylabel('$C$ (pF)');
title('$dC/dT$ vs Temperature swept down');
lgd = legend('show'); lgd.Title.String = 'Run \#';
ylim(d1Cbounds);












