%% Export results Cpnum results to .dat file
function save_Cpnum_data(Cpnum, field_values, comsol_distrib_fname, e, Tc, filename)
    A = cat(2, Cpnum.t_h_dist_w_e', Cpnum.comsolpdf_w_e');
    col_headers = ['T/Tc, Cp/R'];
    file_description = {...
        [sprintf('Heat capacity at Hext = %d kOe, computed numerically ',field_values)];
        ['The computation took into account a distribution of magnetic fields '...
        'computed using COMSOL, and saved in file(s) '...
        comsol_distrib_fname...
        ' as well as the rounding of the transition due to a constant longitudinal field (strain) '...
        sprintf('of e = %.2g as obtained from fitting the data at zero field.', e)];
        ['The zero field transition temperature obtained from the same fit '...
        sprintf('was Tc(H=0) = %.3f K.', Tc)];
        ['The computed heat capacity is a weighted sum of the heat capacity '...
        'at the two closest temperatures at which the distribution of magnetic '...
        'fields was computed in COMSOL.'];
        ['For instance, if the MFD was computed at 0K and 1K, the data point at'...
        '0.2K will be: Cp(T=0.2K, H) = 0.8*Cp(0K, H) + 0.2*Cp(1K, H).'];
        'Any missing data is due to removal of NaN and computational aberrations.'};

    fileID = fopen(filename,'w');
    fprintf(fileID, '# %s\n', file_description{:});
    fprintf(fileID, '%s\n', col_headers);
    fclose(fileID);
    dlmwrite(filename, A, '-append')
end 