function [times1,T_PPMSK,R_LKSK,T_LKSK,BT,VoV,ViV,VoViV,CpF,VarName10,VarName11,VarName12,VarName13,VarName14,VarName15] = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [TIMES1,T_PPMSK,R_LKSK,T_LKSK,BT,VOV,VIV,VOVIV,CPF,VARNAME10,VARNAME11,VARNAME12,VARNAME13,VARNAME14,VARNAME15]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [TIMES1,T_PPMSK,R_LKSK,T_LKSK,BT,VOV,VIV,VOVIV,CPF,VARNAME10,VARNAME11,VARNAME12,VARNAME13,VARNAME14,VARNAME15]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [times1,T_PPMSK,R_LKSK,T_LKSK,BT,VoV,ViV,VoViV,CpF,VarName10,VarName11,VarName12,VarName13,VarName14,VarName15] = importfile('20180912_TmAsO4-LS5342-MS180511-IB_EC_vs_T_94p5Hz_0-180Vcompressive_H=1T.txt',6, 63264);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/09/13 10:39:30

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 6;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
times1 = dataArray{:, 1};
T_PPMSK = dataArray{:, 2};
R_LKSK = dataArray{:, 3};
T_LKSK = dataArray{:, 4};
BT = dataArray{:, 5};
VoV = dataArray{:, 6};
ViV = dataArray{:, 7};
VoViV = dataArray{:, 8};
CpF = dataArray{:, 9};
VarName10 = dataArray{:, 10};
VarName11 = dataArray{:, 11};
VarName12 = dataArray{:, 12};
VarName13 = dataArray{:, 13};
VarName14 = dataArray{:, 14};
VarName15 = dataArray{:, 15};


